### ISSUE TITLE
Segmentation fault with meshes containing 2 holes or more when trying to repair them

### ISSUE THREAD

**Issue by AymericFerreira** [pyvista/pymeshfix#20]
I receive the error message 

```
WARNING:root:DEPRECATED: ``.extract_edges`` is deprecated. Use ``.extract_feature_edges`` > instead.
WARNING- forceNormalConsistence: Basic_TMesh was not orientable. Cut performed.
Fatal Python error: Segmentation fault

Current thread 0x00007f212e597740 (most recent call first):
  File "/mnt/4EB2FF89256EC207/anaconda3/envs/pymesh/lib/python3.7/site- packages/pymeshfix/meshfix.py", line 164 in repair
```

When trying to repair these meshes with 2 holes or more, is there a way to repair this type of meshes ? 

[mini_mesh4.zip](https://github.com/pyvista/pymeshfix/files/4725869/mini_mesh4.zip)
[spinetest.zip](https://github.com/pyvista/pymeshfix/files/4725897/spinetest.zip)

Thank you

**Comment by akaszynski** [comment]
Sorry for the almost month delay!

This has been fixed in the latest `pymeshfix==0.14.1`.  Please upgrade with:
```
pip install pymeshfix --upgrade
```

---

```python
import pymeshfix
import pyvista as pv
mesh = pv.read('mini_mesh4.ply')

cpos = [(-1.3929236007870838, 4.833749352303792, 43.20824934766468),
        (0.4005449689082239, 1.974186544303787, 42.22896653288012),
        (-0.856754747942019, -0.4527997858860601, -0.2468676888139592)]

mfix = pymeshfix.MeshFix(mesh)
mfix.plot(cpos=cpos)
mfix.repair()
mfix.plot(cpos=cpos)
```
![sc0](https://user-images.githubusercontent.com/11981631/86286762-59674100-bbe7-11ea-8131-0ce6722fd3da.png)
![sc1](https://user-images.githubusercontent.com/11981631/86286763-59ffd780-bbe7-11ea-857d-b185456e972e.png)

```python
mesh = pv.read('spinetest.ply')

cpos = [(1.0207721082272285, 5.022610893203265, 5.060511175630762),
        (3.5885198272032457, 1.2667712687692603, 1.113049711178362),
        (-0.9008369720007641, -0.22673492134496934, -0.3702485993480395)]

mfix = pymeshfix.MeshFix(mesh)
mfix.plot(cpos=cpos)
mfix.repair()
mfix.plot(cpos=cpos)
```

![sc2](https://user-images.githubusercontent.com/11981631/86286775-608e4f00-bbe7-11ea-9f5d-8c8cbf2b09c4.png)
![sc3](https://user-images.githubusercontent.com/11981631/86286778-6126e580-bbe7-11ea-8125-95727c8b85d7.png)
